server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9007
    
    

spring:
  application:
    name: micro-sso-server #指定服务名 单点登录
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    host: 192.168.3.193
    port: 6379

  # Spring Cloud Sleuth 中集成 Zipkin ， 配置属性
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth: 
#    sampler:
#      probability: 1.0   
      

# sso token保存时效
sso:
  expire:
    minite: 1440
      
      
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true

    
    
#Feign 本身支持Hystrix    
feign:
   hystrix:
     enabled: true
     
     
# 日志收集
plumelog:
  appName: erp-api
  redisHost: 192.168.3.193
  redisPort: 6379
          
      
