server:
  port: 9001
spring:
  application:
    name: micro-base
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.193:3307/micro_base?&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    
     # 升级到Springboot2.0后，依然是使用jpa、Hibernate来操作mysql，发现Hibernate默认创建的表是myisam引擎，而不是innodb。添加下面的方言即可修改为innodb
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎
    
    cloud:
      config:
        name:  base
        profile:  dev
        label:  master
        uri:  http://127.0.0.1:12000
  
  # 消息总线 使用      
  rabbitmq:
    host:  192.168.184.135 
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
    
# 自定义配置     自定义配置的读取
sms:
  ip: 127.0.0.1    

