server:
  port: 9007
spring:
  application:
    name: micro-search
  redis:
    host: 192.168.3.193
  elasticsearch:
    rest:
      uris: http://192.168.3.193:9200

  main:
    allow-bean-definition-overriding: true



eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true

