server:
  port: 9007
spring:
  application:
    name: micro-search
  data:
    elasticsearch:
      cluster-nodes: 192.168.3.193:9300
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true

