# 自定义请求头tokenName
custom:
  tokenName: token
  security: huoxianzhineng
  expire:
    minite: 1440  # token保存分钟


#admin暴露的接口规则，*表示所有
management:
  endpoints:
    web:
      exposure:
        include: '*'