server:
  port: 6869
spring:
  application:
    name: micro-admin #spring 服务监控中心

  redis:
    host: 192.168.3.193




eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true

