server:
  port: 9011
spring:
  application:
    name: micro-manager
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
 
 
# Zuul路由转发，管理后台微服务网关
zuul:
  routes:
     micro-article: #活动
       path: /article/**   #配置请求URL的请求规则
       serviceId: micro-article   #指定Eureka注册中心中的服务id
     micro-base: #基础
        path: /base/**
        serviceId: micro-base
     micro-friend: #交友
        path: /friend/**
        serviceId: micro-friend
     micro-qa: #问答
        path: /qa/**
        serviceId: micro-qa
     micro-recruit: #招聘
        path: /recruit/**
        serviceId: micro-recruit
     micro-search: #搜索
        path: /search/**
        serviceId: micro-search
     micro-spit: #吐槽
        path: /spit/**
        serviceId: micro-spit
     micro-user: #用户
        path: /user/**
        serviceId: micro-user
        
      
      
# SpringCloud：Zuul网关访问接口超时，type=Gateway Timeout, status=504  
ribbon:
  ReadTimeout: 120000  #请求处理的超时时间
  ConnectTimeout: 30000  #请求连接的超时时间        


jwt:
  config:
    key: test
